name: Deploy to Turtle & Dove

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: deploy-here

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $USER
          echo HELLO WORLD!
          su trustseco
          echo $USER
          echo LOGGED IN
          cd /srv/TrustSECO-DLT
          echo FOUND CORRECT FOLDEER
          git status
          git pull
          echo PULLED
          sudo systemctl restart TrustSECO-DLT
          echo RESTARTED SERVICE
          
          
