name: Deploy to Turtle & Dove
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    container: alpine
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: "turtle.science.uu.nl,dove.science.uu.nl"
        port: 22
        sync: true
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        proxy_host: "up.science.uu.nl"
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_key: ${{ secrets.KEY }}
        script: |
          cd /srv/TrustSECO-DLT
          git pull
          npm install
          sudo systemctl restart TrustSECO-DLT
          
